### ISSUE TITLE
Implement Smart Caching System

### ISSUE THREAD

**Issue by kaidesu** [axiom-labs/rivescript-php#1]
All RiveScript files should be combined into a smart caching system for easy access by the interpreter.

The caching system should take into consideration the names and timestamps of the files to determine if it can simply re-use a previously stored cache instance or create a new one.

The interpreter will then parse through the cached instance of the knowledge tree rather than building the knowledge tree every time a response is requested from the user.

**Comment by johnnymast** [comment]
This cannot be done because the responses are constantly reevaluated. This means that bot parameters can change on the fly and if you have a compiled source (like blade does) it will be biased.
