### ISSUE TITLE
This Library is Lacking Documentation

### ISSUE THREAD

**Issue by berzerk7** [axiom-labs/rivescript-php#20]
Hi, 
I'm really interested in your library, but I don't know how to start, I want to make a PHP project based on RiveScript, can you give me an information about how to start using this library with PHP?
Thank you so much.

**Comment by kaidesu** [comment]
Indeed it is! Here's a rough quickstart from the top of my head.

Keep in mind that this package is still under development and does not fully support all of Rivescript just yet. See the roadmap in the readme for the complete coverage of features.

```php
// Initial set up
$message = 'hello!';

$brain = '~/Code/Example/example.rive'; // Should be the complete path to your .rive file

$rivescript = new Vulcan\Rivescript\Rivescript;
$rivescript->load($brain);

// You now have an instance of rivescript - you may freely send messages to it and get a response

$response = $rivescript->reply(null, $message);

print $response;
```
