### ISSUE TITLE
Failed to download vulcan/verbal-expressions-php from dist: The "https://api.github.com/repos/vulcan-project/verbal-expressions-php/zipball/23018ecf32e0c1de8fe4ed313c38b3e569383999" file could not be downloaded

### ISSUE THREAD

**Issue by nahs** [axiom-labs/rivescript-php#21]
when downloaded from composer write this error
Failed to download vulcan/verbal-expressions-php from dist: The "https://api.github.com/repos/vulcan-project/verbal-expressions-php/zipball/23018ecf32e0c1de8fe4ed313c38b3e569383999" file could not be downloaded

**Comment by tom-berend** [comment]
in the composer.json file, replace
        "vulcan/verbal-expressions-php": "^1.0"
with 
        "verbalexpressions/php-verbal-expressions": "^1.0.0"

I don't know if anyone is accepting pull requests for this repo.
