### ISSUE TITLE
Is this project still being developed?

### ISSUE THREAD

**Issue by johnnymast** [axiom-labs/rivescript-php#23]
Hi!,

My name is Johnny and i have a question. Is this Project still being worked on? And is it stable to be used?

**Comment by kaidesu** [comment]
Can't say I'm actively developing it at the moment. Open to pull requests from anyone who wishes to pick things up :+1: I still have my eye on things.

**Comment by johnnymast** [comment]
I am writing a Laravel based customer service live chat (WebSockets). I
want my customer admins to add their own Rivescript scripts to respond to
new customers on their webshop. But anyway if you need someone to help tell
me what you are missing.
I have already contributed to rivescript-js (but I am no export in the
script language yet).


Op za 9 mei 2020 om 03:41 schreef kai <notifications@github.com>:

**Comment by kirsle** [comment]
@johnnymast if your stack involves PHP, adding rivescript-js to run on the _front-end_ is probably the most surefire bet for getting a bot on your site. You can use JavaScript object macros to make ajax/fetch requests to your back-end PHP scripts to get access to back-end features (database access, etc.)

Other implementations of RiveScript (Go, Python, Java... and rivescript-js run as a node.js server) would run more on the back-end of things. You _could_ create a server-side RiveScript bot with these, but these languages work fundamentally differently than PHP scripts do.

If you'd like to experiment in languages beyond PHP, a [blog post I wrote](https://www.kirsle.net/evolution-of-web-development) summarizes at a high level what other back-end languages look like in comparison to PHP.

**Comment by kaidesu** [comment]
☝️ I've done exactly this with the JS package. I then utilized PHP / MySQL to manage/store my rivescript and compile/pass them through the to the JS interpreter. Worked out well :+1:

**Comment by johnnymast** [comment]
My reason for asking was not advice but to maybe help maintain or add to the project.

**Comment by kaidesu** [comment]
> My reason for asking was not advice but to maybe help maintain or add to the project.

@johnnymast Sorry, a bit late to respond! I'd be happy to find a new maintainer to push this forward :+1: if you're interested, let me know!

**Comment by johnnymast** [comment]
@kaidesu For sure I am interested to take ownership and maintain the project going forward.

**Comment by johnnymast** [comment]
@kaidesu Thank you for bringing me on board. Is there anything you want to add or share maybe a direction?

**Comment by kaidesu** [comment]
Welcome! Nothing in particular other than tackling items to bring the interpreter closer to the RiveScript working draft :+1:

Putting together a big test suite covering all of RiveScript's features might help in the beginning to see where things are at.
